# This version is generated by Cursor and is more efficient

def calculate_distance(left_column, right_column):
    # Sort both lists directly instead of using custom reordering
    left_sorted = sorted(left_column)
    right_sorted = sorted(right_column)
    
    # Use sum with generator expression instead of loop
    return sum(abs(l - r) for l, r in zip(left_sorted, right_sorted))

# Read file more efficiently using list comprehension
with open('day1/input.txt', 'r') as file:
    # Split and convert to int in one go
    left_column, right_column = zip(*(
        map(int, line.split()) for line in file
    ))

print("Left Column:", len(left_column))
print("Right Column:", len(right_column))
print(calculate_distance(left_column, right_column))